# Generated by Django 5.0.1 on 2024-08-19 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_totalstock_remaining_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalstock',
            name='remaining_quantity',
        ),
        migrations.AlterField(
            model_name='totalstock',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AlterField(
            model_name='totalstock',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
